basePath: /
definitions:
  schema.AuthSwag:
    properties:
      password:
        description: 登录密码
        type: string
      user_name:
        description: 登录邮箱
        type: string
    type: object
  schema.CurrentUserSwag:
    properties:
      address:
        type: string
      email:
        description: 用户名
        type: string
      header:
        type: string
      phone:
        description: 电话
        type: string
    type: object
  schema.FarmRecordSwag:
    properties:
      end_time:
        type: string
      oper_name:
        type: string
      start_time:
        type: string
    type: object
  schema.FarmSwag:
    properties:
      end_time:
        type: string
      point:
        type: string
      star_time:
        type: string
    type: object
  schema.PasswordSwag:
    properties:
      new_password:
        description: 新密码
        type: string
      old_password:
        description: 旧密码
        type: string
    type: object
  schema.PicSwag:
    properties:
      end_time:
        type: string
      point:
        type: string
      star_time:
        type: string
    type: object
  schema.PictureSwag:
    properties:
      date:
        type: string
      name:
        type: string
      point:
        type: string
    type: object
  schema.QueryTransNumSwag:
    properties:
      type:
        type: integer
    required:
    - type
    type: object
  schema.RegSwag:
    properties:
      identity:
        description: identity
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - identity
    - password
    - username
    type: object
  schema.RevokeSwag:
    properties:
      identity:
        type: string
      user_name:
        type: string
    type: object
  schema.SensorSwag:
    properties:
      end_time:
        type: string
      point:
        type: string
      star_time:
        type: string
    type: object
  schema.UploadSwag:
    properties:
      point:
        type: string
      raw:
        type: string
      type:
        type: integer
    type: object
  schema.VerifySwag:
    properties:
      hash:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Charge
  license: {}
  title: fabirc bcs API
  version: "1.0"
paths:
  /api/v1/bcs/info:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取区块链状态信息
      tags:
      - 区块链监控
  /api/v1/bcs/points:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 查询所有采集点及其信息数量
      tags:
      - 区块链监控
  /api/v1/bcs/transactions:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.QueryTransNumSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 条件查询交易数
      tags:
      - 区块链监控
  /api/v1/bcs/upload:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.UploadSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 数据上链接口
      tags:
      - 溯源查询
  /api/v1/trace/downloadPic:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.PictureSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: 图片下载
      tags:
      - 溯源查询
  /api/v1/trace/farm:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.FarmSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: 农事数据溯源
      tags:
      - 溯源查询
  /api/v1/trace/pictures:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.PicSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: 图片信息溯源
      tags:
      - 溯源查询
  /api/v1/trace/sensors:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.SensorSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: 传感器数据溯源
      tags:
      - 溯源查询
  /api/v1/trace/verifier:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.VerifySwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: 链上信息检验
      tags:
      - 溯源查询
  /api/v1/user/auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.RevokeSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 用户注销
      tags:
      - 用户管理
  /api/v1/user/currentuser:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取登录用户信息
      tags:
      - 用户管理
  /api/v1/user/header:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户更换头像
      tags:
      - 用户管理
  /api/v1/user/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户登出
      tags:
      - 用户管理
  /api/v1/user/modify:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.CurrentUserSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 修改登录用户信息
      tags:
      - 用户管理
  /api/v1/user/operType:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户头像获取
      tags:
      - 用户管理
  /api/v1/user/password:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.PasswordSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 登录用户修改密码
      tags:
      - 用户管理
  /api/v1/user/record:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.FarmRecordSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户记录上传
      tags:
      - 用户管理
  /api/v1/user/refreshtoken:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 刷新token
      tags:
      - 用户管理
  /api/v1/user/reg:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.RegSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: 注册用户
      tags:
      - 用户管理
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
